unstable_features = true
combine_control_expr = false
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
format_strings = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
imports_granularity = "Crate"
normalize_comments = true
group_imports = "StdExternalCrate"
spaces_around_ranges = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = true
